const DEFAULT_DATA = {
  gaji: 5883000,
  livingItems: [
    { id: 1, name: "Belanja istri",  amount: 1500000 },
    { id: 2, name: "Parkir",         amount: 52000   },
    { id: 3, name: "Bensin",         amount: 100000  },
    { id: 4, name: "Kos",            amount: 600000  },
    { id: 5, name: "Makan",          amount: 620000  },
  ],
  debts: [
    { id:1,  name:"Cairin Salsa",    nominal:15000,   paid:0, end:"Jun 2026", urgency:"urgent", xp:50,  done:false },
    { id:2,  name:"Spaylater Salsa", nominal:40000,   paid:0, end:"Jun 2026", urgency:"urgent", xp:60,  done:false },
    { id:3,  name:"Allobank",        nominal:128333,  paid:0, end:"Mei 2026", urgency:"urgent", xp:100, done:false },
    { id:4,  name:"Neobank Salsa",   nominal:858500,  paid:0, end:"Jun 2026", urgency:"urgent", xp:120, done:false },
    { id:5,  name:"KUR BRI Mas Bag", nominal:955000,  paid:0, end:"Jun 2026", urgency:"urgent", xp:140, done:false },
    { id:6,  name:"Onny",            nominal:1000000, paid:0, end:"Jun 2026", urgency:"urgent", xp:150, done:false },
    { id:7,  name:"Emas BSI",        nominal:610000,  paid:0, end:"Jul 2026", urgency:"soon",   xp:120, done:false },
    { id:8,  name:"Spinjam Salsa",   nominal:330000,  paid:0, end:"Jul 2026", urgency:"soon",   xp:100, done:false },
    { id:9,  name:"Akulaku",         nominal:558000,  paid:0, end:"Jul 2026", urgency:"soon",   xp:110, done:false },
    { id:10, name:"Gadai Emas",      nominal:2600000, paid:0, end:"Agu 2026", urgency:"soon",   xp:200, done:false },
    { id:11, name:"Ceria",           nominal:1230662, paid:0, end:"Agu 2026", urgency:"soon",   xp:160, done:false },
    { id:12, name:"Tiktok Paylater", nominal:351062,  paid:0, end:"Sep 2026", urgency:"safe",   xp:100, done:false },
    { id:13, name:"Mekar",           nominal:375000,  paid:0, end:"Sep 2026", urgency:"safe",   xp:100, done:false },
    { id:14, name:"Briguna",         nominal:480000,  paid:0, end:"Nov 2026", urgency:"safe",   xp:110, done:false },
    { id:15, name:"Tunaiku",         nominal:1992540, paid:0, end:"Apr 2027", urgency:"safe",   xp:180, done:false },
  ],
  achievements: [
    { id:"first",     name:"Hutang Pertama Lunas!", desc:"Bayar satu hutang pertamamu",               icon:"🥇", unlocked:false },
    { id:"jun_clear", name:"Pembersih Juni",         desc:"Lunasi semua hutang deadline Jun 2026",    icon:"🗓️", unlocked:false },
    { id:"half",      name:"Setengah Jalan",          desc:"Lunasi setengah dari total hutangmu",      icon:"🛣️", unlocked:false },
    { id:"naga",      name:"Pembunuh Naga",           desc:"Lunasi hutang Gadai Emas (Rp 2,6 jt)",    icon:"🐉", unlocked:false },
    { id:"freedom",   name:"DEBT FREE!",              desc:"Semua hutang lunas — kebebasan finansial!",icon:"🏆", unlocked:false },
  ],
  xp: 0,
  nextId: 16,
  livingNextId: 6,
};
